const COUNTRIES = [
  { id: "AF", numId: "004", name: "Afghanistan", capital: "Kabul", continent: "Asia" },
  { id: "AL", numId: "008", name: "Albania", capital: "Tirana", continent: "Europe" },
  { id: "DZ", numId: "012", name: "Algeria", capital: "Algiers", continent: "Africa" },
  { id: "AD", numId: "020", name: "Andorra", capital: "Andorra la Vella", continent: "Europe" },
  { id: "AO", numId: "024", name: "Angola", capital: "Luanda", continent: "Africa" },
  { id: "AG", numId: "028", name: "Antigua and Barbuda", capital: "Saint John's", continent: "North America" },
  { id: "AR", numId: "032", name: "Argentina", capital: "Buenos Aires", continent: "South America" },
  { id: "AM", numId: "051", name: "Armenia", capital: "Yerevan", continent: "Asia" },
  { id: "AU", numId: "036", name: "Australia", capital: "Canberra", continent: "Oceania" },
  { id: "AT", numId: "040", name: "Austria", capital: "Vienna", continent: "Europe" },
  { id: "AZ", numId: "031", name: "Azerbaijan", capital: "Baku", continent: "Asia" },
  { id: "BS", numId: "044", name: "Bahamas", capital: "Nassau", continent: "North America" },
  { id: "BH", numId: "048", name: "Bahrain", capital: "Manama", continent: "Asia" },
  { id: "BD", numId: "050", name: "Bangladesh", capital: "Dhaka", continent: "Asia" },
  { id: "BB", numId: "052", name: "Barbados", capital: "Bridgetown", continent: "North America" },
  { id: "BY", numId: "112", name: "Belarus", capital: "Minsk", continent: "Europe" },
  { id: "BE", numId: "056", name: "Belgium", capital: "Brussels", continent: "Europe" },
  { id: "BZ", numId: "084", name: "Belize", capital: "Belmopan", continent: "North America" },
  { id: "BJ", numId: "204", name: "Benin", capital: "Porto-Novo", continent: "Africa" },
  { id: "BT", numId: "064", name: "Bhutan", capital: "Thimphu", continent: "Asia" },
  { id: "BO", numId: "068", name: "Bolivia", capital: "Sucre", altCapitals: ["La Paz"], continent: "South America" },
  { id: "BA", numId: "070", name: "Bosnia and Herzegovina", capital: "Sarajevo", continent: "Europe" },
  { id: "BW", numId: "072", name: "Botswana", capital: "Gaborone", continent: "Africa" },
  { id: "BR", numId: "076", name: "Brazil", capital: "Brasilia", continent: "South America" },
  { id: "BN", numId: "096", name: "Brunei", capital: "Bandar Seri Begawan", continent: "Asia" },
  { id: "BG", numId: "100", name: "Bulgaria", capital: "Sofia", continent: "Europe" },
  { id: "BF", numId: "854", name: "Burkina Faso", capital: "Ouagadougou", continent: "Africa" },
  { id: "BI", numId: "108", name: "Burundi", capital: "Gitega", continent: "Africa" },
  { id: "CV", numId: "132", name: "Cabo Verde", capital: "Praia", altNames: ["Cape Verde"], continent: "Africa" },
  { id: "KH", numId: "116", name: "Cambodia", capital: "Phnom Penh", continent: "Asia" },
  { id: "CM", numId: "120", name: "Cameroon", capital: "Yaounde", continent: "Africa" },
  { id: "CA", numId: "124", name: "Canada", capital: "Ottawa", continent: "North America" },
  { id: "CF", numId: "140", name: "Central African Republic", capital: "Bangui", continent: "Africa" },
  { id: "TD", numId: "148", name: "Chad", capital: "N'Djamena", continent: "Africa" },
  { id: "CL", numId: "152", name: "Chile", capital: "Santiago", continent: "South America" },
  { id: "CN", numId: "156", name: "China", capital: "Beijing", continent: "Asia" },
  { id: "CO", numId: "170", name: "Colombia", capital: "Bogota", continent: "South America" },
  { id: "KM", numId: "174", name: "Comoros", capital: "Moroni", continent: "Africa" },
  { id: "CG", numId: "178", name: "Congo", capital: "Brazzaville", altNames: ["Republic of the Congo", "Congo Republic"], continent: "Africa" },
  { id: "CD", numId: "180", name: "Democratic Republic of the Congo", capital: "Kinshasa", altNames: ["DRC", "DR Congo", "Congo-Kinshasa"], continent: "Africa" },
  { id: "CR", numId: "188", name: "Costa Rica", capital: "San Jose", continent: "North America" },
  { id: "CI", numId: "384", name: "Ivory Coast", capital: "Yamoussoukro", altNames: ["Cote d'Ivoire"], continent: "Africa" },
  { id: "HR", numId: "191", name: "Croatia", capital: "Zagreb", continent: "Europe" },
  { id: "CU", numId: "192", name: "Cuba", capital: "Havana", continent: "North America" },
  { id: "CY", numId: "196", name: "Cyprus", capital: "Nicosia", continent: "Europe" },
  { id: "CZ", numId: "203", name: "Czech Republic", capital: "Prague", altNames: ["Czechia"], continent: "Europe" },
  { id: "DK", numId: "208", name: "Denmark", capital: "Copenhagen", continent: "Europe" },
  { id: "DJ", numId: "262", name: "Djibouti", capital: "Djibouti", continent: "Africa" },
  { id: "DM", numId: "212", name: "Dominica", capital: "Roseau", continent: "North America" },
  { id: "DO", numId: "214", name: "Dominican Republic", capital: "Santo Domingo", continent: "North America" },
  { id: "EC", numId: "218", name: "Ecuador", capital: "Quito", continent: "South America" },
  { id: "EG", numId: "818", name: "Egypt", capital: "Cairo", continent: "Africa" },
  { id: "SV", numId: "222", name: "El Salvador", capital: "San Salvador", continent: "North America" },
  { id: "GQ", numId: "226", name: "Equatorial Guinea", capital: "Malabo", continent: "Africa" },
  { id: "ER", numId: "232", name: "Eritrea", capital: "Asmara", continent: "Africa" },
  { id: "EE", numId: "233", name: "Estonia", capital: "Tallinn", continent: "Europe" },
  { id: "SZ", numId: "748", name: "Eswatini", capital: "Mbabane", altNames: ["Swaziland"], continent: "Africa" },
  { id: "ET", numId: "231", name: "Ethiopia", capital: "Addis Ababa", continent: "Africa" },
  { id: "FJ", numId: "242", name: "Fiji", capital: "Suva", continent: "Oceania" },
  { id: "FI", numId: "246", name: "Finland", capital: "Helsinki", continent: "Europe" },
  { id: "FR", numId: "250", name: "France", capital: "Paris", continent: "Europe" },
  { id: "GA", numId: "266", name: "Gabon", capital: "Libreville", continent: "Africa" },
  { id: "GM", numId: "270", name: "Gambia", capital: "Banjul", altNames: ["The Gambia"], continent: "Africa" },
  { id: "GE", numId: "268", name: "Georgia", capital: "Tbilisi", continent: "Asia" },
  { id: "DE", numId: "276", name: "Germany", capital: "Berlin", continent: "Europe" },
  { id: "GH", numId: "288", name: "Ghana", capital: "Accra", continent: "Africa" },
  { id: "GR", numId: "300", name: "Greece", capital: "Athens", continent: "Europe" },
  { id: "GD", numId: "308", name: "Grenada", capital: "Saint George's", continent: "North America" },
  { id: "GT", numId: "320", name: "Guatemala", capital: "Guatemala City", continent: "North America" },
  { id: "GN", numId: "324", name: "Guinea", capital: "Conakry", continent: "Africa" },
  { id: "GW", numId: "624", name: "Guinea-Bissau", capital: "Bissau", continent: "Africa" },
  { id: "GY", numId: "328", name: "Guyana", capital: "Georgetown", continent: "South America" },
  { id: "HT", numId: "332", name: "Haiti", capital: "Port-au-Prince", continent: "North America" },
  { id: "HN", numId: "340", name: "Honduras", capital: "Tegucigalpa", continent: "North America" },
  { id: "HU", numId: "348", name: "Hungary", capital: "Budapest", continent: "Europe" },
  { id: "IS", numId: "352", name: "Iceland", capital: "Reykjavik", continent: "Europe" },
  { id: "IN", numId: "356", name: "India", capital: "New Delhi", continent: "Asia" },
  { id: "ID", numId: "360", name: "Indonesia", capital: "Jakarta", continent: "Asia" },
  { id: "IR", numId: "364", name: "Iran", capital: "Tehran", continent: "Asia" },
  { id: "IQ", numId: "368", name: "Iraq", capital: "Baghdad", continent: "Asia" },
  { id: "IE", numId: "372", name: "Ireland", capital: "Dublin", continent: "Europe" },
  { id: "IL", numId: "376", name: "Israel", capital: "Jerusalem", continent: "Asia" },
  { id: "IT", numId: "380", name: "Italy", capital: "Rome", continent: "Europe" },
  { id: "JM", numId: "388", name: "Jamaica", capital: "Kingston", continent: "North America" },
  { id: "JP", numId: "392", name: "Japan", capital: "Tokyo", continent: "Asia" },
  { id: "JO", numId: "400", name: "Jordan", capital: "Amman", continent: "Asia" },
  { id: "KZ", numId: "398", name: "Kazakhstan", capital: "Astana", continent: "Asia" },
  { id: "KE", numId: "404", name: "Kenya", capital: "Nairobi", continent: "Africa" },
  { id: "KI", numId: "296", name: "Kiribati", capital: "Tarawa", continent: "Oceania" },
  { id: "KP", numId: "408", name: "North Korea", capital: "Pyongyang", continent: "Asia" },
  { id: "KR", numId: "410", name: "South Korea", capital: "Seoul", continent: "Asia" },
  { id: "XK", numId: "-99", name: "Kosovo", capital: "Pristina", continent: "Europe" },
  { id: "KW", numId: "414", name: "Kuwait", capital: "Kuwait City", continent: "Asia" },
  { id: "KG", numId: "417", name: "Kyrgyzstan", capital: "Bishkek", continent: "Asia" },
  { id: "LA", numId: "418", name: "Laos", capital: "Vientiane", continent: "Asia" },
  { id: "LV", numId: "428", name: "Latvia", capital: "Riga", continent: "Europe" },
  { id: "LB", numId: "422", name: "Lebanon", capital: "Beirut", continent: "Asia" },
  { id: "LS", numId: "426", name: "Lesotho", capital: "Maseru", continent: "Africa" },
  { id: "LR", numId: "430", name: "Liberia", capital: "Monrovia", continent: "Africa" },
  { id: "LY", numId: "434", name: "Libya", capital: "Tripoli", continent: "Africa" },
  { id: "LI", numId: "438", name: "Liechtenstein", capital: "Vaduz", continent: "Europe" },
  { id: "LT", numId: "440", name: "Lithuania", capital: "Vilnius", continent: "Europe" },
  { id: "LU", numId: "442", name: "Luxembourg", capital: "Luxembourg City", continent: "Europe" },
  { id: "MG", numId: "450", name: "Madagascar", capital: "Antananarivo", continent: "Africa" },
  { id: "MW", numId: "454", name: "Malawi", capital: "Lilongwe", continent: "Africa" },
  { id: "MY", numId: "458", name: "Malaysia", capital: "Kuala Lumpur", altCapitals: ["Putrajaya"], continent: "Asia" },
  { id: "MV", numId: "462", name: "Maldives", capital: "Male", continent: "Asia" },
  { id: "ML", numId: "466", name: "Mali", capital: "Bamako", continent: "Africa" },
  { id: "MT", numId: "470", name: "Malta", capital: "Valletta", continent: "Europe" },
  { id: "MH", numId: "584", name: "Marshall Islands", capital: "Majuro", continent: "Oceania" },
  { id: "MR", numId: "478", name: "Mauritania", capital: "Nouakchott", continent: "Africa" },
  { id: "MU", numId: "480", name: "Mauritius", capital: "Port Louis", continent: "Africa" },
  { id: "MX", numId: "484", name: "Mexico", capital: "Mexico City", continent: "North America" },
  { id: "FM", numId: "583", name: "Micronesia", capital: "Palikir", continent: "Oceania" },
  { id: "MD", numId: "498", name: "Moldova", capital: "Chisinau", continent: "Europe" },
  { id: "MC", numId: "492", name: "Monaco", capital: "Monaco", continent: "Europe" },
  { id: "MN", numId: "496", name: "Mongolia", capital: "Ulaanbaatar", continent: "Asia" },
  { id: "ME", numId: "499", name: "Montenegro", capital: "Podgorica", continent: "Europe" },
  { id: "MA", numId: "504", name: "Morocco", capital: "Rabat", continent: "Africa" },
  { id: "MZ", numId: "508", name: "Mozambique", capital: "Maputo", continent: "Africa" },
  { id: "MM", numId: "104", name: "Myanmar", capital: "Naypyidaw", altNames: ["Burma"], continent: "Asia" },
  { id: "NA", numId: "516", name: "Namibia", capital: "Windhoek", continent: "Africa" },
  { id: "NR", numId: "520", name: "Nauru", capital: "Yaren", continent: "Oceania" },
  { id: "NP", numId: "524", name: "Nepal", capital: "Kathmandu", continent: "Asia" },
  { id: "NL", numId: "528", name: "Netherlands", capital: "Amsterdam", altNames: ["Holland"], continent: "Europe" },
  { id: "NZ", numId: "554", name: "New Zealand", capital: "Wellington", continent: "Oceania" },
  { id: "NI", numId: "558", name: "Nicaragua", capital: "Managua", continent: "North America" },
  { id: "NE", numId: "562", name: "Niger", capital: "Niamey", continent: "Africa" },
  { id: "NG", numId: "566", name: "Nigeria", capital: "Abuja", continent: "Africa" },
  { id: "MK", numId: "807", name: "North Macedonia", capital: "Skopje", altNames: ["Macedonia"], continent: "Europe" },
  { id: "NO", numId: "578", name: "Norway", capital: "Oslo", continent: "Europe" },
  { id: "OM", numId: "512", name: "Oman", capital: "Muscat", continent: "Asia" },
  { id: "PK", numId: "586", name: "Pakistan", capital: "Islamabad", continent: "Asia" },
  { id: "PW", numId: "585", name: "Palau", capital: "Ngerulmud", continent: "Oceania" },
  { id: "PS", numId: "275", name: "Palestine", capital: "Ramallah", continent: "Asia" },
  { id: "PA", numId: "591", name: "Panama", capital: "Panama City", continent: "North America" },
  { id: "PG", numId: "598", name: "Papua New Guinea", capital: "Port Moresby", continent: "Oceania" },
  { id: "PY", numId: "600", name: "Paraguay", capital: "Asuncion", continent: "South America" },
  { id: "PE", numId: "604", name: "Peru", capital: "Lima", continent: "South America" },
  { id: "PH", numId: "608", name: "Philippines", capital: "Manila", continent: "Asia" },
  { id: "PL", numId: "616", name: "Poland", capital: "Warsaw", continent: "Europe" },
  { id: "PT", numId: "620", name: "Portugal", capital: "Lisbon", continent: "Europe" },
  { id: "QA", numId: "634", name: "Qatar", capital: "Doha", continent: "Asia" },
  { id: "RO", numId: "642", name: "Romania", capital: "Bucharest", continent: "Europe" },
  { id: "RU", numId: "643", name: "Russia", capital: "Moscow", continent: "Europe" },
  { id: "RW", numId: "646", name: "Rwanda", capital: "Kigali", continent: "Africa" },
  { id: "KN", numId: "659", name: "Saint Kitts and Nevis", capital: "Basseterre", continent: "North America" },
  { id: "LC", numId: "662", name: "Saint Lucia", capital: "Castries", continent: "North America" },
  { id: "VC", numId: "670", name: "Saint Vincent and the Grenadines", capital: "Kingstown", continent: "North America" },
  { id: "WS", numId: "882", name: "Samoa", capital: "Apia", continent: "Oceania" },
  { id: "SM", numId: "674", name: "San Marino", capital: "San Marino", continent: "Europe" },
  { id: "ST", numId: "678", name: "Sao Tome and Principe", capital: "Sao Tome", continent: "Africa" },
  { id: "SA", numId: "682", name: "Saudi Arabia", capital: "Riyadh", continent: "Asia" },
  { id: "SN", numId: "686", name: "Senegal", capital: "Dakar", continent: "Africa" },
  { id: "RS", numId: "688", name: "Serbia", capital: "Belgrade", continent: "Europe" },
  { id: "SC", numId: "690", name: "Seychelles", capital: "Victoria", continent: "Africa" },
  { id: "SL", numId: "694", name: "Sierra Leone", capital: "Freetown", continent: "Africa" },
  { id: "SG", numId: "702", name: "Singapore", capital: "Singapore", continent: "Asia" },
  { id: "SK", numId: "703", name: "Slovakia", capital: "Bratislava", continent: "Europe" },
  { id: "SI", numId: "705", name: "Slovenia", capital: "Ljubljana", continent: "Europe" },
  { id: "SB", numId: "090", name: "Solomon Islands", capital: "Honiara", continent: "Oceania" },
  { id: "SO", numId: "706", name: "Somalia", capital: "Mogadishu", continent: "Africa" },
  { id: "ZA", numId: "710", name: "South Africa", capital: "Pretoria", altCapitals: ["Cape Town", "Bloemfontein"], continent: "Africa" },
  { id: "SS", numId: "728", name: "South Sudan", capital: "Juba", continent: "Africa" },
  { id: "ES", numId: "724", name: "Spain", capital: "Madrid", continent: "Europe" },
  { id: "LK", numId: "144", name: "Sri Lanka", capital: "Sri Jayawardenepura Kotte", altCapitals: ["Colombo", "Kotte"], continent: "Asia" },
  { id: "SD", numId: "729", name: "Sudan", capital: "Khartoum", continent: "Africa" },
  { id: "SR", numId: "740", name: "Suriname", capital: "Paramaribo", continent: "South America" },
  { id: "SE", numId: "752", name: "Sweden", capital: "Stockholm", continent: "Europe" },
  { id: "CH", numId: "756", name: "Switzerland", capital: "Bern", continent: "Europe" },
  { id: "SY", numId: "760", name: "Syria", capital: "Damascus", continent: "Asia" },
  { id: "TW", numId: "158", name: "Taiwan", capital: "Taipei", continent: "Asia" },
  { id: "TJ", numId: "762", name: "Tajikistan", capital: "Dushanbe", continent: "Asia" },
  { id: "TZ", numId: "834", name: "Tanzania", capital: "Dodoma", altCapitals: ["Dar es Salaam"], continent: "Africa" },
  { id: "TH", numId: "764", name: "Thailand", capital: "Bangkok", continent: "Asia" },
  { id: "TL", numId: "626", name: "Timor-Leste", capital: "Dili", altNames: ["East Timor"], continent: "Asia" },
  { id: "TG", numId: "768", name: "Togo", capital: "Lome", continent: "Africa" },
  { id: "TO", numId: "776", name: "Tonga", capital: "Nuku'alofa", continent: "Oceania" },
  { id: "TT", numId: "780", name: "Trinidad and Tobago", capital: "Port of Spain", continent: "North America" },
  { id: "TN", numId: "788", name: "Tunisia", capital: "Tunis", continent: "Africa" },
  { id: "TR", numId: "792", name: "Turkey", capital: "Ankara", altNames: ["Turkiye"], continent: "Europe" },
  { id: "TM", numId: "795", name: "Turkmenistan", capital: "Ashgabat", continent: "Asia" },
  { id: "TV", numId: "798", name: "Tuvalu", capital: "Funafuti", continent: "Oceania" },
  { id: "UG", numId: "800", name: "Uganda", capital: "Kampala", continent: "Africa" },
  { id: "UA", numId: "804", name: "Ukraine", capital: "Kyiv", continent: "Europe" },
  { id: "AE", numId: "784", name: "United Arab Emirates", capital: "Abu Dhabi", altNames: ["UAE"], continent: "Asia" },
  { id: "GB", numId: "826", name: "United Kingdom", capital: "London", altNames: ["UK"], continent: "Europe" },
  { id: "US", numId: "840", name: "United States", capital: "Washington D.C.", altNames: ["USA", "United States of America"], altCapitals: ["Washington", "Washington DC"], continent: "North America" },
  { id: "UY", numId: "858", name: "Uruguay", capital: "Montevideo", continent: "South America" },
  { id: "UZ", numId: "860", name: "Uzbekistan", capital: "Tashkent", continent: "Asia" },
  { id: "VU", numId: "548", name: "Vanuatu", capital: "Port Vila", continent: "Oceania" },
  { id: "VA", numId: "336", name: "Vatican City", capital: "Vatican City", continent: "Europe" },
  { id: "VE", numId: "862", name: "Venezuela", capital: "Caracas", continent: "South America" },
  { id: "VN", numId: "704", name: "Vietnam", capital: "Hanoi", continent: "Asia" },
  { id: "YE", numId: "887", name: "Yemen", capital: "Sanaa", continent: "Asia" },
  { id: "ZM", numId: "894", name: "Zambia", capital: "Lusaka", continent: "Africa" },
  { id: "ZW", numId: "716", name: "Zimbabwe", capital: "Harare", continent: "Africa" }
];
